### ISSUE TITLE
More flexibilty for run inputs - config

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/radiance-folder-structure#4]
- What if someone wants to use `epw` instead of `wea`?
- How does one configure date-time for studies? Do they need to edit wea file beforehand?

We need to develop a config file or options from command line to support such cases. Here is a quick start.

```yaml
## config.yaml
weather_file: new_location.epw   # this can be a wea or an epw
analysis_period:
  start: 2 Feb
  end: 28 Feb
analysis_hours:
  start: 8
  end: 17
```

**Comment by mostaphaRoudsari** [comment]
Here is a proposal JSON schema for daylight factor.

```js
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Daylight Factor Recipe",
    "description": "Schema for daylight-factor recipe.",
    "type": "object",
    "properties": {
        "recipe": {
            "description": "Recipe name.",
            "enum": [
                "daylight factor"
            ],
            "readOnly": true
        },
        "study_name": {
            "description": "A unique name for this study.",
            "type": "string"
        },
        "grids": {
            "type": "array",
            "description": "List of grid names.",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "Grid name. A grid with the same name must be available inside grids folder."
                    },
                    "count": {
                        "type": "integer",
                        "description": "Number of points in this grid. This is useful for breaking down the grids in smaller pieces for parallel runs."
                    }
                },
                "required": [
                    "name"
                ]
            }
        },
        "options": {
            "description": "Rtrace command options.",
            "type": "string"
        }
    },
    "required": [
        "recipe",
        "study_name",
        "grids"
    ],
    "examples": [
        {
            "recipe": "daylight_factor",
            "study_name": "sample_run",
            "grids": [
                {
                    "name": "room.pts",
                    "count": 112
                }
            ],
            "options": "-ab 3"
        }
    ]
}
```

and example will look like this:

```js
{
    "recipe": "daylight_factor",
    "study_name": "sample_run",
    "grids": [
        {
            "name": "room.pts",
            "count": 112
        }
    ],
    "options": "-ab 3"
}
```
or if you prefer `yaml` it will be like this:

```yaml
recipe: daylight_factor
study_name: sample_run
grids:
- name: room.pts
  count: 112
options: "-ab 3"
```
